# Generated by Django 4.2 on 2025-01-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0003_especialidad_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='owner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
