# Generated by Django 4.2 on 2025-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySql', '0004_usuario_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='owner_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
